#!/usr/bin/python

import sys
import dbus


device_name = sys.argv[1]
bus = dbus.SystemBus()
device = bus.get_object('org.freedesktop.Hal', device_name)
dev_iface = dbus.Interface(device,
               dbus_interface='org.freedesktop.Hal.Device.Volume')

print "Trying to unmount device %s" % device_name
dev_iface.Unmount([])
